In [1]:
# apply => dataframe 에 파이썬 함수를 적용 할 수 있다.

import pandas as pd

df = pd.DataFrame({
    "가로" : [10,20,30,40,5,6,77,81,95],
    "세로" : [91,84,73,68,5,4,32,20,11],
})

df

   가로  세로
0  10  91
1  20  84
2  30  73
3  40  68
4   5   5
5   6   4
6  77  32
7  81  20
8  95  11

In [4]:
def getVolume(row):
    return row["가로"] + row["세로"]


//하나의 행이 인자가 되어 계산을 수행한다.
df['부피'] = df.apply(getVolume, axis=1)
df

   가로  세로   부피
0  10  91  101
1  20  84  104
2  30  73  103
3  40  68  108
4   5   5   10
5   6   4   10
6  77  32  109
7  81  20  101
8  95  11  106